### ISSUE TITLE
eif文件是怎么转成图片

### ISSUE THREAD

**Issue by Cphilo** [Pearyman/eif#1]
这个repo没有源码，想问下下载下来的eif文件怎么转成图片的呢

**Comment by Pearyman** [comment]
eif 是通过qq将图片合成成一个表情包的。你可以那多张图片通过qq来合成eif。

你把下下来的eif直接拉到qq下就可以看到图片了。

[查看gif图](http://7xw3j4.com1.z0.glb.clouddn.com/biaoqing2.gif)

![](http://7xw3j4.com1.z0.glb.clouddn.com/biaoqing2.gif)
