### ISSUE TITLE
Is there an exact method to modify the group name of a set of face in the latest version of QQ ?

### ISSUE THREAD

**Issue by zymelaii** [Pearyman/eif#2]
RT.

**Comment by Pearyman** [comment]
still use qq? 😅

**Comment by zymelaii** [comment]
yep, it is a pity that it's still a necessity for me to deal with most social matters, like school notifications etc. Undoubtedly what I'm trying to do is a time-wasteful case, but I really need to sort out my stickers in an much more efficient way in QQ (maybe).

whispering: fxxking shit tencent 😅
